/*
 Boost Software License - Version 1.0 - August 17th, 2003

 Permission is hereby granted, free of charge, to any person or organization
 obtaining a copy of the software and accompanying documentation covered by
 this license (the "Software") to use, reproduce, display, distribute,
 execute, and transmit the Software, and to prepare derivative works of the
 Software, and to permit third-parties to whom the Software is furnished to
 do so, all subject to the following:

 The copyright notices in the Software and this entire statement, including
 the above license grant, this restriction and the following disclaimer,
 must be included in all copies of the Software, in whole or in part, and
 all derivative works of the Software, unless such copies or derivative
 works are solely in the form of machine-executable object code generated by
 a source language processor.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 DEALINGS IN THE SOFTWARE.
 */

/*
 Code from:
 Williams, Anthony. C++ concurrency in action. London, 2012
 Available at: https://www.manning.com/books/c-plus-plus-concurrency-in-action
 */

#ifndef THREAD_POOL_H
#define THREAD_POOL_H

#include <atomic>
#include <condition_variable>
#include <deque>
#include <future>
#include <memory>
#include <mutex>
#include <thread>
#include <type_traits>
#include <utility>
#include <vector>

// Just before listing 8.4
class join_threads
{
  std::vector<std::thread>& threads;
public:
  explicit join_threads(std::vector<std::thread>& threads_);
  ~join_threads();
};

// Listing 9.2
class function_wrapper
{
  struct impl_base {
    virtual void call()=0;
    virtual ~impl_base() {}
  };
  std::unique_ptr<impl_base> impl;
  template<typename F>
  struct impl_type: impl_base
  {
    F f;
    impl_type(F&& f_): f(std::move(f_)) {}
    void call() { f(); }
  };
public:
  template<typename F>
  function_wrapper(F&& f):
    impl(new impl_type<F>(std::move(f)))
  {}

  void operator()() { impl->call(); }
  function_wrapper() = default;
  function_wrapper(function_wrapper&& other):
    impl(std::move(other.impl))
  {}

  function_wrapper& operator=(function_wrapper&& other)
  {
    impl=std::move(other.impl);
    return *this;
  }

  bool has_value () const {
    return (bool)impl;
  }

  function_wrapper(const function_wrapper&)=delete;
  function_wrapper(function_wrapper&)=delete;
  function_wrapper& operator=(const function_wrapper&)=delete;
};

class thread_pool
{
  std::deque<function_wrapper> work_queue; /* protected by mu */
  std::condition_variable cv;
  std::mutex mu;

  /* per-thread index inside its owning pool; sentinel value for any thread
   * that is not a worker (e.g., the main thread) */
  static size_t & my_id_ref() {
    thread_local size_t my_id = static_cast<size_t>(-1);
    return my_id;
  }

  void worker_thread(size_t my_id)
  {
    my_id_ref() = my_id;
    for(;;){
      std::unique_lock<std::mutex> lk(mu);
      cv.wait(lk, [&]{ return !work_queue.empty() || done; });
      if(done && work_queue.empty())
        return;
      function_wrapper task = std::move(work_queue.front());
      work_queue.pop_front();
      lk.unlock();
      task();
    }
  }

  std::atomic_bool done;
  std::vector<std::thread> threads;
  join_threads joiner;

  unsigned const thread_count;

public:
  template<typename FunctionType>
  std::future<typename std::invoke_result<FunctionType>::type>
  submit(FunctionType f)
  {
    typedef typename std::invoke_result<FunctionType>::type result_type;

    std::packaged_task<result_type()> task(std::move(f));
    std::future<result_type> res(task.get_future());
    {
      std::unique_lock<std::mutex> lk(mu);
      work_queue.push_back(std::move(task));
      cv.notify_one();
    }
    return res;
  }

  thread_pool(unsigned const n_threads = 1):
    done(false),
    joiner(threads),
    thread_count(n_threads)
  {
    try
    {
      for(unsigned i=0;i<thread_count;++i)
      {
        threads.push_back(
          std::thread(&thread_pool::worker_thread, this,
                      static_cast<size_t>(i)));
      }
    }
    catch(...)
    {
      {
        std::unique_lock<std::mutex> lk(mu);
        done=true;
      }
      cv.notify_all();
      throw;
    }
  }

  ~thread_pool()
  {
    {
      std::unique_lock<std::mutex> lk(mu);
      done=true;
    }
    cv.notify_all();
  }

  size_t get_id() const {
    size_t const id = my_id_ref();
    return id == static_cast<size_t>(-1) ? threads.size() : id;
  }
};


#endif
